version: '3'
services:
  api:
    build: .
    volumes:
     - ./src:/app
    restart: always
    environment:
      STAGE: TEST
      TRIP_TO_CARBON_URL: https://api.triptocarbon.xyz/v1/footprint
    ports:
     - 8080:80
    tty: true
    stdin_open: true
